apro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('projects/', include('projects.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path

from projects import views

urlpatterns = [
    path('', views.index, name='projects'),
    path('<int:project_id>', views.project, name='project'),
    path('search', views.search, name='search'),

]

projects/models.py
from datetime import datetime
from email.policy import default

from django.db import models

from contractors.models import Contractor
from pms.models import ProjectManager
from projects import choices


class Project(models.Model):
    name = models.CharField(max_length=200)
    main_photo = models.ImageField(upload_to='photos/projects/%Y/%m')
    city = models.CharField(
        max_length=30, choices=choices.city_choices, default='BOG')
    state = models.CharField(
        max_length=30, choices=choices.state_choices, default='CUN')
    scope = models.CharField(max_length=50, choices=choices.scope_choices)
    zone = models.CharField(max_length=4, choices=choices.zone_choices)
    location_lat = models.FloatField()
    location_long = models.FloatField()
    is_active = models.BooleanField(default=False)
    # Budget
    budget_allocated = models.IntegerField()
    dollar = models.FloatField()
    # Time
    goal_time = models.IntegerField()
    contractor = models.ForeignKey(Contractor, on_delete=models.DO_NOTHING)
    # Project Manager
    project_manager = models.ForeignKey(
        ProjectManager, on_delete=models.DO_NOTHING)
    is_published = models.BooleanField(default=True)
    create_date = models.DateTimeField(default=datetime.now, blank=True)
    # Gantt data
    fascia_start = models.DateTimeField(default=datetime.now, blank=True)
    fascia_end = models.DateTimeField(default=datetime.now, blank=True)
    fascia_parent = models.CharField(
        default='', max_length=20, choices=choices.ganttimage_choices)
    paint_start = models.DateTimeField(default=datetime.now, blank=True)
    paint_end = models.DateTimeField(default=datetime.now, blank=True)
    paint_parent = models.CharField(
        default='', max_length=20, choices=choices.ganttimage_choices)
    signage_start = models.DateTimeField(default=datetime.now, blank=True)
    signage_end = models.DateTimeField(default=datetime.now, blank=True)
    signage_parent = models.CharField(
        default='', max_length=20, choices=choices.ganttimage_choices)
    fundation_start = models.DateTimeField(default=datetime.now, blank=True)
    fundation_end = models.DateTimeField(default=datetime.now, blank=True)
    fundation_parent = models.CharField(
        default='', max_length=20, choices=choices.ganttimage_choices)
    lifting_start = models.DateTimeField(default=datetime.now, blank=True)
    lifting_end = models.DateTimeField(default=datetime.now, blank=True)
    lifting_parent = models.CharField(
        default='', max_length=20, choices=choices.ganttimage_choices)

    def __str__(self):
        return self.name


class GanttImage(models.Model):
    # Completion
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING)
    fascia_completion = models.DecimalField(max_digits=3, decimal_places=2)
    spreader_completion = models.DecimalField(max_digits=3, decimal_places=2)
    paint_completion = models.DecimalField(max_digits=3, decimal_places=2)
    signage_completion = models.DecimalField(max_digits=3, decimal_places=2)
    fundation_completion = models.DecimalField(max_digits=3, decimal_places=2)
    lifting_completion = models.DecimalField(max_digits=3, decimal_places=2)
    report_date = models.DateTimeField(default=datetime.now, blank=True)

    
    def __str__(self):
        return str(self.report_date)

projects/views.py
from django.contrib.postgres import search
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render

from projects.choices import city_choices, scope_choices, state_choices, zone_choices, goaltime_choices, budget_choices

from .models import Project, GanttImage


def index(request):
    projects = Project.objects.order_by(
        '-create_date').filter(is_published=True)

    paginator = Paginator(projects, 3)
    page = request.GET.get('page')
    paged_projects = paginator.get_page(page)
    #ganttimage = GanttImage.objects.filter(project_id=projects.id).lates('reporte_date')
    context = {
        'projects': paged_projects,
        
    }
    return render(request, 'projects/projects.html', context)


def project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    ganttimage = GanttImage.objects.filter(project_id=project_id).latest('report_date')
    #ganttimage = get_object_or_404(GanttImage, project_id=project_id).latest('report_date')
    
    context = {
        'project': project,
        'ganttimage': ganttimage
    }
    return render(request, 'projects/project.html', context)


def search(request):
    queryset_list = Project.objects.order_by('-create_date')

    # Keywords
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(
                description__icontains=keywords)

    # City
    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list = queryset_list.filter(city__iexact=city)

    # State
    if 'state' in request.GET:
        state = request.GET['state']
        if state:
            queryset_list = queryset_list.filter(state__iexact=state)

    # Term of work, goal_time
    if 'goal_time' in request.GET:
        goal_time = request.GET['goal_time']
        if goal_time:
            queryset_list = queryset_list.filter(goal_time__lte=goal_time)

    # Budget allocated
    if 'budget_allocated' in request.GET:
        budget_allocated = request.GET['budget_allocated']
        if budget_allocated:
            queryset_list = queryset_list.filter(
                budget_allocated__lte=budget_allocated)

    # Scope of Project (i.e design, fuels, image)
    if 'scope' in request.GET:
        scope = request.GET['scope']
        if scope:
            queryset_list = queryset_list.filter(scope__iexact=scope)

    context = {
        'state_choices': state_choices,
        'budget_choices': budget_choices,
        'scope_choices': scope_choices,
        'goaltime_choices': goaltime_choices,
        'projects': queryset_list,
        'values': request.GET
    }
    return render(request, 'projects/search.html', context)

templates/projects/_projects.html
{% extends 'base.html' %}
{% block content %}
        <!-- Showcase-->
    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">Proyectos</h1>
                    <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
                </div>
            </div>
        </div>
    </section>
        <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'index' %}">
                            <i class="fas fa-home"></i> Home</a>
                    </li>
                    <li class="breadcrumb-item active"> Proyectos</li>
                </ol>
            </nav>
        </div>
    </section>
    <!-- Projects -->
    <section id="projects" class="py-4">
        <div class="container">
            <div class="row">       
                <!-- Loop of Projects -->
                {% if projects %}
                {% for project in projects %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card listing-preview">
                        <img class="card-img-top" src="{{ project.main_photo.url }}" alt="">
                        <div class="card-img-overlay">
                            <h2>
                                <span class="badge badge-secondary text-white">92%</span>
                            </h2>
                        </div>
                        <div class="card-body">
                            <div class="listing-heading text-center">
                                <h4 class="text-primary">{{ project.name }}</h4>
                                <p>
                                    <i class="fas fa-map-marker text-secondary"></i> {{ project.city }} {{ project.state }}</p>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-12">
                                    <i class="fas fa-calendar"></i> Duración: {{ project.goal_time }}</div>

                            </div>
                            <div class="row py-2 text-secondary">
                                <div class="col-12">
                                    <i class="fas fa-list"></i> Presupuesto: ${{ project.budget_allocated  }} </div>

                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-12">
                                    <i class="fas fa-user"></i> {{ project.contractor }}</div>
                            </div>
                            <div class="row text-secondary pb-2">
                                <div class="col-12">
                                    <i class="fas fa-clock"></i> {{ project.create_date | timesince }}</div>
                            </div>
                            <hr>
                            <a href="#" class="btn btn-primary btn-block">Más Info</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <div class="col-md-12">
                    <p>No hay proyectos Disponibles</p>
                </div>
                {% endif %}


            </div>

    
{% endblock content %}

templates/projects/ganttimage.html
<h1>Gantt Image Template</h1>

templates/projects/project.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<!-- Showcase-->
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">{{ project.name }}</h1>
                <p class="lead">{{ project.get_city_display }}, {{ project.get_state_display }}</p>
                <p class="lead"><strong>Zona:</strong> {{project.get_zone_display}}
                </p>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'projects' %}">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item active"> Proyectos</li>
            </ol>
        </nav>
    </div>
</section>

<!-- Project Pictures -->
<section id="listing" class="py-2">
    <div class="container">
        <a href="{% url 'index' %}" class="btn btn-light mb-4">Regreso a Buscador</a>
        <div class="row">
            <div class="col-md-9">
                <!-- Home Main Image -->
                <img src="{{ project.main_photo.url }}" alt="" class="img-main img-fluid mb-3">
                <div class="card-img-overlay">
                        <h2>
                            <span class="badge badge-success text-white">{{ganttimage.fascia_completion}}</span>
                        </h2>
                    </div>

                <!-- Fields -->
                <div class="row mb-5 fields">
                    <div class="col-md-6">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-clock"></i> Plazo:
                                <span class="float-right">{{ project.goal_time }}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-money-bill-wave-alt"></i> Presupuesto:
                                <span class="float-right">${{ project.budget_allocated | intword }}</span>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-glasses"></i> Gerente:
                                <span class="float-right">{{ project.project_manager }}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-calendar"></i> Fecha inicio:
                                <span class="float-right">{{ project.create_date }}</span>
                            </li>
                        </ul>
                    </div>
                    
                </div>
            </div>
            <!--Contractor Info-->
            <div class="float-right col-md-3">
                <div class="card mb-3">
                    <img class="card-img-top" src="{{ project.contractor.contractor_logo.url }}" alt="Seller of the month">
                    <div class="card-body">
                        <h5 class="card-title">Contratista</h5>
                        <h6 class="text-secondary">{{ project.contractor }}</h6>
                    </div>
                </div>
                <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Comentar</button>
            </div>
        </div>  
</section>
<section>
    <div class="container">
        <a href="{% url 'index' %}" class="btn btn-light mb-4">Regreso a Buscador</a>
        <div class="row">
            <div class="text-secondary">
                <i class="fas fa-eye":before></i><span><strong> Gantt Chart: </strong> {{ project.name }}</span>
            </div>
            
            <div class="float-right col-md-12">
                    {% include 'partials/_ganttimage.html'%}
            </div>      
        </div>
    </div>
</section> 


{% endblock content %}

templates/projects/projects.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}
    <!-- Showcase-->
    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">Proyectos</h1>
                    <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'index' %}">
                            <i class="fas fa-home"></i> Home</a>
                    </li>
                    <li class="breadcrumb-item active"> Proyectos</li>
                </ol>
            </nav>
        </div>
    </section>

    <!-- Projects -->
    <section id="projects" class="py-4">
        <div class="container">
            <div class="row">       
                <!-- Loop of Projects -->
                {% if projects %}
                {% for project in projects %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card listing-preview">
                        <img class="card-img-top" src="{{ project.main_photo.url }}" alt="">
                        <div class="card-img-overlay">
                            <h2>
                                {% if project.is_published%}
                                <span class="badge badge-success text-white">Activo</span>
                                {% else %}
                                <span class="badge badge-warning text-white">Inactivo</span>
                                {%endif%}
                                
                            </h2>
                        </div>
                        <div class="card-body">
                            <div class="listing-heading text-center">
                                <h4 class="text-primary">{{ project.name }}</h4>
                                <p>
                                    <i class="fas fa-map-marker text-secondary"></i> {{ project.get_city_display }}, {{ project.get_state_display }}</p>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-12">
                                    <i class="fas fa-calendar"></i> Duración: {{ project.goal_time }} days</div>

                            </div>
                            <div class="row py-2 text-secondary">
                                <div class="col-12">
                                    <i class="fas fa-list"></i> Presupuesto: ${{ project.budget_allocated | intcomma }} </div>

                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-12">
                                    <i class="fas fa-user"></i> {{ project.contractor }}</div>
                            </div>
                            <div class="row text-secondary pb-2">
                                <div class="col-12">
                                    <i class="fas fa-clock"></i> {{ project.create_date | timesince }}</div>
                            </div>
                            <hr>
                            <a href="{% url 'project' project.id %}" class="btn btn-primary btn-block">Más Info</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <div class="col-md-12">
                    <p>No hay proyectos Disponibles</p>
                </div>
                {% endif %}


            </div>

    
    <!-- Pagination-->
    <div class="row">
      <div class="col-md-12">
      {% if projects.has_other_pages %}
        <ul class="pagination">
          {% if projects.has_previous %}
            <li class="page-item">
              <a href="?page={{projects.previous_page_number}}" class="page-link">&laquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link">&laquo;</a>
            </li>
          {% endif %}
          {% for i in projects.paginator.page_range %}
            {% if projects.number == i %}
              <li class="page-item active">
                <a class="page-link">{{i}}</a>
              </li>
            {% else %}
              <li class="page-item">
                <a href="?page={{i}}" class="page-link">{{i}}</a>
              </li>
            {% endif %}
          {% endfor %}
          {% if projects.has_next %}
            <li class="page-item">
              <a href="?page={{projects.next_page_number}}" class="page-link">&raquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link">&raquo;</a>
            </li>
          {% endif %}
        </ul>
      {% endif %}
      </div>
    </div>
        </div>
    </section>
{% endblock content %}

templates/projects/search.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<!-- Showcase-->
<section id="showcase">
    <div class="container text-center">
        <div class="home-search p-5">
            <div class="overlay p-5">
                <h1 class="display-4 mb-4">
                    Buscador de Proyectos
                </h1>
                <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae quas, asperiores
                    eveniet vel nostrum magnam
                    voluptatum tempore! Consectetur, id commodi!</p>
                <div class="search">
                    <form action="{% url 'search' %}">
                        <!-- Form Row 1 -->
                        <div class="form-row">
                            <div class="col-md-4 mb-3">
                                <label class="sr-only">Keywords</label>
                                <input type="text" name="keywords" class="form-control" placeholder="Palabras (Canopy, island, etc)">
                            </div>
                            <div class="col-md-4 mb-3">
                                <label class="sr-only">Tipo de Proyecto</label>
                                <select name="scope" class="form-control">
                                    <option selected="true" disabled="disabled">Tipo (Todos)</option>
                                    {% for key, value in scope_choices %}
                                       <option value="{{ key }}"
                                       {% if key == values.scope %}
                                        selected
                                       {% endif %}
                                       >{{ value | safe }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-4 mb-3">
                                <label class="sr-only">Departamento</label>
                                <select name="state" class="form-control">
                                    <option selected="true" disabled="disable">Departamento (Todos)</option>
                                    {% for key, value in state_choices %}
                                       <option value="{{ key }}"
                                       {% if key == values.state %}
                                        selected
                                       {% endif %}
                                       >{{ value | safe }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <!-- Form Row 2 -->
                        <div class="form-row">
                            <div class="col-md-6 mb-3">
                                <label class="sr-only">Presupuesto</label>
                                <select name="budget_allocated" class="form-control">
                                    <option selected="true" disabled="disabled">Max Presupuesto (Todos)</option>
                                    {% for key, value in budget_choices  %}
                                    <option value="{{key}}"
                                    {% if key == values.budget_allocated %}
                                        selected
                                       {% endif %}
                                    >{{value}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-6 mb-3">
                                <select name="goal_time" class="form-control" id="type">
                                    <option selected="true" disabled="disabled">Max Duración (Cualquiera)</option>
                                    {% for key, value in goaltime_choices  %}
                                    <option value="{{key}}"
                                    {% if key == values.goal_time %}
                                        selected
                                       {% endif %}
                                    >{{value}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <button class="btn btn-secondary btn-block mt-4" type="submit">Buscar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'projects'%}">Proyectos</a>
          </li>
          <li class="breadcrumb-item active"> Tablero</li>
        </ol>
      </nav>
    </div>
  </section>

<!-- Projects -->
<section id="listings" class="py-4">
      <div class="container">
          <div class="row">       
              <!-- Loop of Projects -->
              {% if projects %}
              {% for project in projects %}
              <div class="col-md-6 col-lg-4 mb-4">
                  <div class="card listing-preview">
                      <img class="card-img-top" src="{{ project.main_photo.url }}" alt="">
                      <div class="card-img-overlay">
                          <h2>
                              <span class="badge badge-secondary text-white">92%</span>
                          </h2>
                      </div>
                      <div class="card-body">
                          <div class="listing-heading text-center">
                              <h4 class="text-primary">{{ project.name }}</h4>
                              <p>
                                  <i class="fas fa-map-marker text-secondary"></i> {{ project.get_city_display }}, {{ project.get_state_display }}</p>
                          </div>
                          <hr>
                          <div class="row py-2 text-secondary">
                              <div class="col-12">
                                  <i class="fas fa-calendar"></i> Duración: {{ project.goal_time }} days</div>
                          </div>
                          <div class="row py-2 text-secondary">
                                <div class="col-12">
                                  <i class="fas fa-list"></i> Presupuesto: ${{ project.budget_allocated | intcomma }} 
                                </div>
                          </div>
                          <hr>
                          <div class="row py-2 text-secondary">
                              <div class="col-12">
                                  <i class="fas fa-user"></i> {{ project.contractor }}</div>
                          </div>
                          <div class="row text-secondary pb-2">
                                <div class="col-12">
                                  <i class="fas fa-clock"></i> {{ project.create_date | timesince }}</div>
                          </div>
                          <hr>
                          <a href="{% url 'project' project.id %}" class="btn btn-primary btn-block">Más Info</a>
                      </div>
                  </div>
              </div>
              {% endfor %}
              {% else %}
              <div class="col-md-12">
                  <p>No hay proyectos Disponibles</p>
              </div>
              {% endif %}

            </div>
</section>
    
{% endblock content %}